# Generated by Django 4.2 on 2024-04-16 13:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menusection",
            name="url",
            field=models.CharField(max_length=200, verbose_name="ссылка"),
        ),
    ]


__all__ = ()
