# Generated by Django 4.2 on 2024-04-17 12:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0002_alter_menusection_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menusection",
            name="url",
            field=models.CharField(
                max_length=200,
                unique=True,
                verbose_name="ссылка, если named url,"
                " то формат записи: 'namespace:name'",
            ),
        ),
    ]


__all__ = ()
