# Generated by Django 4.2 on 2024-04-17 13:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0003_alter_menusection_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menusection",
            name="url",
            field=models.CharField(
                help_text="Если named url, "
                "то формат записи: 'namespace:name'",
                max_length=200,
                unique=True,
                verbose_name="ссылка",
            ),
        ),
    ]


__all__ = ()
